pipeline {
    agent any
    
    stages {
        stage('Setup Buildx') {
            steps {
                sh 'docker context create --docker host=unix:///var/run/docker.sock main-context'
                sh 'docker context use main-context'
                sh 'docker buildx create --use main-context --name main-builder --config ~/.docker/buildkitd.toml'
                sh 'docker buildx use main-builder'
                sh 'docker buildx inspect --bootstrap'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                // Enable specific architectures
                sh 'docker run --privileged --rm tonistiigi/binfmt --install arm64,arm/v6,arm/v7'
                
                // Or enable all architectures
                // sh 'docker run --privileged --rm tonistiigi/binfmt --install all'
                
                // Set buildx as the default builder
                sh 'docker buildx install'
            }
        }
        
        // Add more stages for your actual build tasks...
    }
}
